export const API_URL = 'https://service.sovetromantica.com/v1/list?limit=20'
export const SR_IMAGE_URL = (id: string, slug: string) => `https://chitoge.sovetromantica.com/anime/${id}_${slug}/images/${id}.jpg`
export const ANIME_URL = (id: string) => `https://service.sovetromantica.com/v1/anime/${id}`
export const ANIME_FIRST_EPISODE_URL = (id: string, slug: string, dubOrSub: string) => `https://scu2.sovetromantica.com/anime/${id}_${slug}/images/episode_1_${dubOrSub}.jpg`
export const BACKEND_API_URL = 'http://localhost:3030/'

export const DORAMAS = [
    {
        "anime_description": "Огава Мики (Шисон Джун / Shison Jun) мечтала о красивой жизни прекрасной девушки, поэтому переехала из сельской местности в большой город. Мики просто красавица, есть работа, подруги, прекрасная жизнь - мечта сбывается, но у нее есть один большой секрет: она - трансгендер. Несмотря на красивую девичью внешность, Мики - мужчина. Однажды, перед ней появляется Гото Тадаоми (Мачида Кейта / Machida Keita), с которым они окончили одну и ту же школу. Тадаоми удивлен внешнему виду Мики и заявляет, что нуждается в помощи, ведь у него нет ни денег ни знакомых в городе, поэтому они начинают жить вместе.",
        "anime_episodes": 4,
        "anime_folder": "joshi-teki-seikatsu",
        "anime_id": 678,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/678_joshi-teki-seikatsu/images/678.jpg",
        "anime_keywords": "",
        "anime_name": "Joshi teki Seikatsu",
        "anime_name_russian": "Жить как девушка",
        "anime_ongoing": 0,
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_soft_raw_link": "",
        "anime_studio": 0,
        "anime_year": 2018,
        "episode_current_dub": 4,
        "episode_current_sub": 0
    },
    {
        "anime_description": "История начинается после перевода таинственной студентки в среднюю школу для девочек. После ее перевода в школе начали происходить странные события, что перевернуло вверх ногами жизнь других студентов.",
        "anime_episodes": 6,
        "anime_folder": "crow-s-blood",
        "anime_id": 679,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/679_crow-s-blood/images/679.jpg",
        "anime_keywords": "",
        "anime_name": "Crow’s Blood",
        "anime_name_russian": "Кровь ворона",
        "anime_ongoing": 0,
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_soft_raw_link": "",
        "anime_studio": 0,
        "anime_year": 2016,
        "episode_current_dub": 6,
        "episode_current_sub": 0
    },

    {
        "anime_description": "Нам Хон Джу, видит во сне будущее и это будущее не всегда прекрасно, часто ей снятся трагические события, которые должны произойти с другими людьми. Но что она может сделать, ее никто не послушает даже, если попытается рассказать человеку о грядущей опасности. Однажды девушке приснился незнакомый мужчина, они были очень близки, а на утро она встретила молодого прокурора Чон Дже Чана и сразу же узнала в нем парня из своего сна. И пусть он не верит, но Хон Джу уже знает, что это знакомство не случайность.",
        "anime_episodes": 32,
        "anime_folder": "while-you-were-sleeping",
        "anime_id": 680,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/680_while-you-were-sleeping/images/680.jpg",
        "anime_keywords": "",
        "anime_name": "While you were sleeping",
        "anime_name_russian": "Пока ты спала",
        "anime_ongoing": 0,
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_soft_raw_link": "",
        "anime_studio": 0,
        "anime_year": 2017,
        "episode_current_dub": 32,
        "episode_current_sub": 0
    },
    {
        "anime_description": "У мужчины никогда не было девушки из-за его аллергии на других людей при малейшем прикосновении, поэтому молодой человек всю свою жизнь вынужден носить маску на лице и скрывать все свое тело под одеждой... Ему приходится проживать свой каждый день в одиночестве, у него нет друзей, но он красив, богат и успешен. Однажды он встречает девушку-робота, Аджи 3, и влюбляется в нее.",
        "anime_episodes": 32,
        "anime_folder": "i-m-not-a-robot",
        "anime_id": 709,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/709_i-m-not-a-robot/images/709.jpg",
        "anime_keywords": "",
        "anime_name": "I'm not a robot!",
        "anime_name_russian": "Я не робот!",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2017
    },
    {
        "anime_description": "Сюжет дорамы «Особый закон романтики» разворачивается вокруг молодого судьи по имени Чон Ый Чан. Каждый день ему приходиться рассматривать гражданские иски и принимать взвешенные решения. Однажды в его жизни появляется милая девушка Со Чжи Хе. Она случайно столкнулась с ним на улице и для Ый Чана это была настоящая любовь с первого взгляда. Вскоре эту пару ждет настоящая интрига, и если хотите узнать, как будут развиваться дальнейшие отношения героев, смотрите дораму.",
        "anime_episodes": 6,
        "anime_folder": "romance-special-law",
        "anime_id": 710,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/710_romance-special-law/images/710.jpg",
        "anime_keywords": "",
        "anime_name": "Romance special law",
        "anime_name_russian": "Особый закон романтики",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2017
    },
    {
        "anime_description": "Переведённая ученица Симизу Саюри (Огури Юи) решила взойти на вершину школы и сформировать новую элиту \"Ханагуми\", которая будет противостоять действующей верхушке, студенческому совету женской школы \"Арасигаока\".",
        "anime_episodes": 10,
        "anime_folder": "majimuri-gakuen",
        "anime_id": 711,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/711_majimuri-gakuen/images/711.jpg",
        "anime_keywords": "",
        "anime_name": "Majimuri Gakuen",
        "anime_name_russian": "Школа \"Мадзимури\"",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2018
    },
    {
        "anime_description": "Дорама «Цветок и зверь» расскажет трогательную историю любви. Только первая любовь, искренняя и чистая может быть такой нежной и ранимой. В основе сюжете – взаимоотношения подростков и их личные переживания первой любви.\r\nПо случайному стечению обстоятельств Хе становится защитником новенькой ученицы Куми в старшей школе Японии. Однако на деле события разворачиваются совершенно по-другому и сердце милой Куми в замешательстве. Дружба, испытания, доверие и любовь – главные этапы человеческих отношений на пути к взрослой жизни, которые предстоит пройти главным героям.",
        "anime_episodes": 10,
        "anime_folder": "hana-ni-kedamono",
        "anime_id": 715,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/715_hana-ni-kedamono/images/715.jpg",
        "anime_keywords": "",
        "anime_name": "Hana ni Kedamono",
        "anime_name_russian": "Цветок и зверь",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2017
    },
    {
        "anime_description": "На первый взгляд Муги Авая (Дори Сакурада) и Ханаби Ясураока (Мию Ёсимото) кажутся идеальной парой. Оба привлекательные и общительные, они отлично подходят друг другу. Так что окружающие даже и не подозревают, что объединяет эту пару совсем не любовь, а горькая тайна, которую они скрывают. Дело в том, что оба безнадежно влюблены и, к сожалению, не друг в друга. Они изображают пару, стараясь спастись от боли и одиночества. Муги влюблен в Аканэ Минагаву, учительницу, которая одно время была его репетитором. Ханаби тоже любит учителя, с которым с детства знакома - Наруми Каная. Молодой человек с давних пор является другом семьи. Два подростка ищут друг в друге утешение, убежище, где хоть ненадолго можно спрятаться от страданий по тем, рядом с кем им быть не суждено. Пусть их и объединяет физическая близость, но смогут ли они по-настоящему избавить друг друга от одиночества? Или всё так и останется по-прежнему? ",
        "anime_episodes": 12,
        "anime_folder": "kuzu-no-honkai",
        "anime_id": 739,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/739_kuzu-no-honkai/images/739.jpg",
        "anime_keywords": "",
        "anime_name": "Kuzu no Honkai",
        "anime_name_russian": "Тайные желания отвергнутых",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2017
    },
    {
        "anime_description": "BL веб-сериал о четырёх парнях, которые запутались в любви. ",
        "anime_episodes": 12,
        "anime_folder": "dark-blue-the-moonlight",
        "anime_id": 740,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/740_dark-blue-the-moonlight/images/740.jpg",
        "anime_keywords": "",
        "anime_name": "Dark Blue & The Moonlight",
        "anime_name_russian": "Темно-синий лунный свет",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2017
    },
    {
        "anime_description": "Старшеклассник Итиго Куросаки с детства был способен видеть призраков. Однажды, встряв в схватку со странным призрачным монстром, Итиго погибает, но оказывается возвращен к жизни ангелом смерти-синигами по имени Рукия. Из-за нелепой случайности Рукия лишается всех своих сил, которые попадают к Итиго. Отныне Итиго — новый синигами и борец со злыми духами, а Рукия — простая смертная девушка, вынужденная стать наставником для молодого охламона.",
        "anime_episodes": 1,
        "anime_folder": "bleach",
        "anime_id": 741,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/741_bleach/images/741.jpg",
        "anime_keywords": "",
        "anime_name": "Bleach",
        "anime_name_russian": "Блич",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2018
    },
    {
        "anime_description": "Старшеклассники До Чжин (Чан Ки Ён) и Чже И (Чжин Ки Чжу) стали друг для друга первой любовью. Отец парня, Хи Чжэ (Хо Джун Хо) - психопат. Он убивает родителей Чже И. Впоследствии молодые люди расстаются.\r\nСпустя годы До Чжин становится детективом. Он заботится о семьях жертв, пытаясь таким образом искупить ужасающее преступление своего отца. Чже И пошла по стопам своей знаменитой матери и тоже стала популярной актрисой. После убийства родителей девушка страдает от посттравматического стрессового расстройства.\r\nОднажды До Чжин и Чже И встречаются вновь.",
        "anime_episodes": 32,
        "anime_folder": "yiriwa-anajwoe",
        "anime_id": 742,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/742_yiriwa-anajwoe/images/742.jpg",
        "anime_keywords": "",
        "anime_name": "Yiriwa Anajwoe",
        "anime_name_russian": "Приди и обними меня",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2018
    },
    {
        "anime_description": "Косэй Арима был вундеркиндом-пианистом, с малых лет выигрывавшим множество состязаний. Конечно, знатоки отмечали, что по стилю малыш скорее техник, чем виртуоз, и даже дали ему кличку \"метроном\", но судьи не считали это недостатком. В одиннадцать лет Арима потерял мать – единственного учителя и наставника – и перестал слышать свою игру. Боль от потери преградила ему путь к роялю, и Косэй словно застыл во времени, два года общаясь лишь с друзьями детства Цубаки и Рётой. Стремясь расшевелить парня, Цубаки вытащила его на \"двойное свидание\" – тут все и началось.\r\nНедостающей участницей оказалась золотоволосая девушка Каори Миядзоно, на редкость импульсивная и энергичная. Из-за нее вся компания вместо кино или шопинга оказалась в концертном зале, где Каори участвовала в скрипичном конкурсе. Косэй с первых же нот понял (чужую игру он слушать мог), что в музыке девушка – его антипод: вместо феноменально точного следования партитуре она играет, как душе угодно! Что ж, противоположности сходятся, и после пары дней знакомства Миядзоно твердо взяла дело в свои руки и предложила Ариме аккомпанировать ей на втором этапе конкурса.",
        "anime_episodes": 1,
        "anime_folder": "shigatsu-wa-kimi-no-uso",
        "anime_id": 745,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/745_shigatsu-wa-kimi-no-uso/images/745.jpg",
        "anime_keywords": "",
        "anime_name": "Shigatsu wa Kimi no Uso",
        "anime_name_russian": "Твоя апрельская ложь",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2016
    },
    {
        "anime_description": "Фильм «Оборотни: Волчья стая» снят по мотивам одноименного аниме 1999 года по сценарию Осии Мамору. Сюжет разворачивается в 2029 году на фоне противостояния сторонников и противников воссоединения Северной и Южной Кореи. Главный герой, боец элитного специального подразделения по борьбе с террористами, которые все активнее прибегают к радикальным мерам и насилию выражая свое несогласие с правительством. В это непростое время он знакомится с девушкой, встреча с которой поставит героя перед сложным выбором.",
        "anime_episodes": 1,
        "anime_folder": "illang-the-wolf-brigade-2018",
        "anime_id": 746,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/746_illang-the-wolf-brigade-2018/images/746.jpg",
        "anime_keywords": "",
        "anime_name": "Illang: The Wolf Brigade 2018",
        "anime_name_russian": "Оборотни: Волчья стая",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2018
    },
    {
        "anime_description": "Загадочная авария в туннелях под мостом-шоссе Токио Бэй Аква Лайн ставит на уши все аварийные подразделения мегаполиса. Шеф МЧС Японии созывает всех, чтобы найти причину аварии, и возможные решения сложившейся проблемы. Они еще не знают, что это только начало. Огромное существо, известное как Годзилла, встало на путь разрушения...",
        "anime_episodes": 1,
        "anime_folder": "shin-godzilla-2016",
        "anime_id": 747,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/747_shin-godzilla-2016/images/747.jpg",
        "anime_keywords": "",
        "anime_name": "Shin Godzilla 2016",
        "anime_name_russian": "Годзилла: Возрождение (2016)",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2016
    },
    {
        "anime_description": "Какие земные организмы самые живучие? Конечно же, тараканы! Вот их вместе с плесенью и забросили в XXI веке на Марс, чтобы качали кислород, топили льды и готовили планету к заселению. Люди прибыли принимать работу через 500 лет. Увы, вместо радостных вестей экипаж успел сообщить, что двухметровые разумные тараканы-сепаратисты выражают серьезную озабоченность сложившейся ситуацией – то есть, попросту говоря, жрут астронавтов живьем! А время торопит, человечество выкашивает смертельная болезнь, от которой можно только бежать, да пока некуда…",
        "anime_episodes": 1,
        "anime_folder": "terra-formars",
        "anime_id": 748,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/748_terra-formars/images/748.jpg",
        "anime_keywords": "",
        "anime_name": "Terra Formars",
        "anime_name_russian": "Терраформирование",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2016
    },
    {
        "anime_description": "Переломный момент для Страны восходящего солнца наступил в 1600 году, когда Япония переживала не самые лучшие времена, разделившись на две противоборствующие стороны. Армии Востока и Запада должны были встретиться для решающей битвы за власть на равнине Сэкигахара. Лидеры двух враждующих коалиций были вассалами мудрого и справедливого правителя Тоетоми Хидэеси, объединившего земли. После его смерти остался малолетний сын. Полководец Исида Мицунари, и его оппонент Токугава Иэясу воспользовавшись внутренними распрями, решили захватить бразды правления.\r\nКаждый считал, что справедливость на его стороне. У обоих могущественных и влиятельных лидеров был опыт в ведении сражений, но имелось отличие в методах борьбы. Претендент на власть Токугава действовал не только силой, но и хитростью. Тактическим ходом, способным принести Восточной коалиции победу стал сбор информации о численности войск. Токугава отправил в стан врага преданную девушку, красивую шпионку.",
        "anime_episodes": 1,
        "anime_folder": "sekigahara-2017",
        "anime_id": 749,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/749_sekigahara-2017/images/749.jpg",
        "anime_keywords": "",
        "anime_name": "Sekigahara 2017",
        "anime_name_russian": "Битва при Сэкигахара",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2017
    },
    {
        "anime_description": "Татэваки Сётаро молодой парень, который еще не нашел свое призвание в жизни и поэтому устроился на работу в местный палеонтологический музей. По заданию руководства Татэваки отправляется в особняк к остеологу Сакурако за скелетом лисы. Задание не из приятных, да и эксперт мягко говоря странная. Больше всего девушка любит изучать кости, зарытые под ногами и не только животных, но и человеческие.\r\nПохоже, что удача ей улыбнулась и вместе с Татэваки они отправились в лес, где нашли скелет женщины. Следователь привлек парочку к расследованию обстоятельств ее смерти. Так состоялось знакомство парня без определенной цели в жизни и девушки одержимой изучением костей.",
        "anime_episodes": 10,
        "anime_folder": "beautiful-bones-sakurako-s-investigation",
        "anime_id": 750,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/750_beautiful-bones-sakurako-s-investigation/images/750.jpg",
        "anime_keywords": "",
        "anime_name": "Beautiful Bones: Sakurako's Investigation",
        "anime_name_russian": "Кости, зарытые под ногами Сакурако",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2017
    },
    {
        "anime_description": "Старшеклассник Сакагами Такуми не очень хорошо ладит с одноклассниками, чтобы как-то исправить ситуацию учитель \"записывает\" его в Исполнительный комитет по работе с населением. Нарусэ Джун также входит в состав комитета. Из-за перенесенных в детстве потрясений, когда она начинает говорить, у неё болит живот, поэтому Джун предпочитает молчать и общаться по смс. Но вот незадача: Такуми и Джун нужно подготовить для выступления на городском мероприятии мюзикл, да и сама девушка хочет петь...",
        "anime_episodes": 1,
        "anime_folder": "kokoro-ga-sakebitagatterunda",
        "anime_id": 751,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/751_kokoro-ga-sakebitagatterunda/images/751.jpg",
        "anime_keywords": "",
        "anime_name": "Kokoro ga Sakebitagatterunda",
        "anime_name_russian": "Сердцу хочется кричать",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2017
    },
    {
        "anime_description": "Японский бастард одного из Джостаров по имени Дзёсукэ Хигасиката с детства владеет необычными способностями. Но пришли времена, когда всяческие суперспособности стали обнаруживаться у некоторых жителей его родного города.",
        "anime_episodes": 1,
        "anime_folder": "jojo-s-bizarre-adventure-diamond-is-unbreakable",
        "anime_id": 752,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/752_jojo-s-bizarre-adventure-diamond-is-unbreakable/images/752.jpg",
        "anime_keywords": "",
        "anime_name": "JoJo's Bizarre Adventure: Diamond is Unbreakable",
        "anime_name_russian": "Невероятные приключения ДжоДжо",
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_studio": 0,
        "anime_year": 2017
    },
    {
        "anime_description": "Старшеклассница Хан Со Ён, которая мечтает стать моделью, меняется телами со знаменитым в Корее топ-моделью На Джин Уком.",
        "anime_episodes": 6,
        "anime_folder": "my-runaway",
        "anime_id": 766,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/766_my-runaway/images/766.jpg",
        "anime_keywords": "",
        "anime_name": "My runway",
        "anime_name_russian": "Мой подиум",
        "anime_ongoing": 0,
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_soft_raw_link": "",
        "anime_studio": 0,
        "anime_year": 2017,
        "episode_current_dub": 6,
        "episode_current_sub": 0
    },
    {
        "anime_description": "Главные герои мистической комедийной дорамы «Страшно прекрасный» О Иль Сун и Ю Филип связаны общей судьбой. Когда у одного начинается светлая полоса в жизни, другого постигают неудачи. Вместе с тем Иль Су обладает необычной способностью, она сценарист и все ее выдумки со временем становятся явью. Ю Филип популярная супер-звезда, но у него есть слабость, он боится темных замкнутых пространств, крови и всего потустороннего. Конечно же герои просто обязаны встретиться и разрешить загадку судьбы.",
        "anime_episodes": 32,
        "anime_folder": "lovely-horribly",
        "anime_id": 774,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/774_lovely-horribly/images/774.jpg",
        "anime_keywords": "",
        "anime_name": "Lovely Horribly",
        "anime_name_russian": "Страшно прекрасный",
        "anime_ongoing": 0,
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_soft_raw_link": "",
        "anime_studio": 0,
        "anime_year": 2018,
        "episode_current_dub": 3,
        "episode_current_sub": 0
    },
    {
        "anime_description": "Красивых людей любят и почитают. Пред их ногами расстилается весь мир...\r\nКасанэ на редкость уродлива, и из-за этого над ней издеваются одноклассники. Ее мать была очень известной актрисой необыкновенной красоты. До того, как умереть, она передала Касанэ свою помаду со словами, что, если ей когда-либо станет очень трудно, она должна нанести её и поцеловать то, чего она действительно желает.\r\nНо в самом ли деле этот подарок на память - благословение? Или же всё-таки проклятие?",
        "anime_episodes": 0,
        "anime_folder": "kasane-beauty-and-fate",
        "anime_id": 876,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/876_kasane-beauty-and-fate/images/876.jpg",
        "anime_keywords": "",
        "anime_name": "Kasane: Beauty and Fate",
        "anime_name_russian": "Касанэ",
        "anime_ongoing": 0,
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_soft_raw_link": "",
        "anime_studio": 0,
        "anime_year": 2018,
        "episode_current_dub": 1,
        "episode_current_sub": 0
    },
    {
        "anime_description": "Цукисиро Каноко, которая в свои 26 лет не знает, что такое любовь, работает редактором в отделе литературы издательства \"Рёкусэн\". По долгу службы девушке приходится иметь дело с различными писателями, среди которых и Кагая Саку. Он один из популярных писателей издательства, но, как и Каноко, не может любить.",
        "anime_episodes": 8,
        "anime_folder": "bungaku-shojo",
        "anime_id": 1035,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/1035_bungaku-shojo/images/1035.jpg",
        "anime_keywords": "Корейщина",
        "anime_name": "Bungaku Shojo",
        "anime_name_russian": "Литературная девушка",
        "anime_ongoing": 0,
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_soft_raw_link": "",
        "anime_studio": 0,
        "anime_year": 2018,
        "episode_current_dub": 8,
        "episode_current_sub": 0
    },
    {
        "anime_description": "Ли Кан Хун - генеральный директор корейского филиала одной из самых крупных компаний мира D.O.L. Он идеальный мужчина: высокий красавец с прекрасным телом. Его считают самым сексуальным парнем. Но он холоден к людям вокруг.\r\nОднажды его похищают, но чудом ему удаётся сбежать от плохих парней. Окровавленный, он падает в обморок прямо перед ветеринарной клиникой. Главная героиня, Ча Юн Со - ветеринар этой клиники, находит его и лечит.",
        "anime_episodes": 20,
        "anime_folder": "noble-my-love",
        "anime_id": 1036,
        "anime_img_url": "https://chitoge.sovetromantica.com/anime/1036_noble-my-love/images/1036.jpg",
        "anime_keywords": "Корейщина",
        "anime_name": "Noble, My Love",
        "anime_name_russian": "Моя благородная любовь",
        "anime_ongoing": 0,
        "anime_paused": 0,
        "anime_shikimori": 0,
        "anime_soft_raw_link": "",
        "anime_studio": 0,
        "anime_year": 2015,
        "episode_current_dub": 11,
        "episode_current_sub": 0
    }

]